//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 09/11/2021 14:00:59
namespace Terrasoft.Configuration.OData
{
    /// <summary>
    /// There are no comments for CampaignTargetSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CampaignTargetSingle")]
    public partial class CampaignTargetSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<CampaignTarget>
    {
        /// <summary>
        /// Initialize a new CampaignTargetSingle object.
        /// </summary>
        public CampaignTargetSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CampaignTargetSingle object.
        /// </summary>
        public CampaignTargetSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CampaignTargetSingle object.
        /// </summary>
        public CampaignTargetSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<CampaignTarget> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedBy")]
        public virtual global::Terrasoft.Configuration.OData.ContactSingle CreatedBy
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CreatedBy == null))
                {
                    this._CreatedBy = new global::Terrasoft.Configuration.OData.ContactSingle(this.Context, GetPath("CreatedBy"));
                }
                return this._CreatedBy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ContactSingle _CreatedBy;
        /// <summary>
        /// There are no comments for ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedBy")]
        public virtual global::Terrasoft.Configuration.OData.ContactSingle ModifiedBy
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ModifiedBy == null))
                {
                    this._ModifiedBy = new global::Terrasoft.Configuration.OData.ContactSingle(this.Context, GetPath("ModifiedBy"));
                }
                return this._ModifiedBy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ContactSingle _ModifiedBy;
        /// <summary>
        /// There are no comments for Campaign in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Campaign")]
        public virtual global::Terrasoft.Configuration.OData.CampaignSingle Campaign
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Campaign == null))
                {
                    this._Campaign = new global::Terrasoft.Configuration.OData.CampaignSingle(this.Context, GetPath("Campaign"));
                }
                return this._Campaign;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.CampaignSingle _Campaign;
        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Contact")]
        public virtual global::Terrasoft.Configuration.OData.ContactSingle Contact
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Contact == null))
                {
                    this._Contact = new global::Terrasoft.Configuration.OData.ContactSingle(this.Context, GetPath("Contact"));
                }
                return this._Contact;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ContactSingle _Contact;
        /// <summary>
        /// There are no comments for CampaignTargetStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CampaignTargetStatus")]
        public virtual global::Terrasoft.Configuration.OData.CampaignTargetStatusSingle CampaignTargetStatus
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CampaignTargetStatus == null))
                {
                    this._CampaignTargetStatus = new global::Terrasoft.Configuration.OData.CampaignTargetStatusSingle(this.Context, GetPath("CampaignTargetStatus"));
                }
                return this._CampaignTargetStatus;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.CampaignTargetStatusSingle _CampaignTargetStatus;
        /// <summary>
        /// There are no comments for CurrentStep in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrentStep")]
        public virtual global::Terrasoft.Configuration.OData.CampaignStepSingle CurrentStep
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CurrentStep == null))
                {
                    this._CurrentStep = new global::Terrasoft.Configuration.OData.CampaignStepSingle(this.Context, GetPath("CurrentStep"));
                }
                return this._CurrentStep;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.CampaignStepSingle _CurrentStep;
        /// <summary>
        /// There are no comments for NextStep in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("NextStep")]
        public virtual global::Terrasoft.Configuration.OData.CampaignStepSingle NextStep
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._NextStep == null))
                {
                    this._NextStep = new global::Terrasoft.Configuration.OData.CampaignStepSingle(this.Context, GetPath("NextStep"));
                }
                return this._NextStep;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.CampaignStepSingle _NextStep;
        /// <summary>
        /// There are no comments for PassedStep in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PassedStep")]
        public virtual global::Terrasoft.Configuration.OData.CampaignStepSingle PassedStep
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PassedStep == null))
                {
                    this._PassedStep = new global::Terrasoft.Configuration.OData.CampaignStepSingle(this.Context, GetPath("PassedStep"));
                }
                return this._PassedStep;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.CampaignStepSingle _PassedStep;
    }
    /// <summary>
    /// There are no comments for CampaignTarget in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.EntitySet("CampaignTarget")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CampaignTarget")]
    public partial class CampaignTarget : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public virtual global::System.Nullable<global::System.Guid> Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _Id;
        partial void OnIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property CreatedById in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedById")]
        public virtual global::System.Nullable<global::System.Guid> CreatedById
        {
            get
            {
                return this._CreatedById;
            }
            set
            {
                this.OnCreatedByIdChanging(value);
                this._CreatedById = value;
                this.OnCreatedByIdChanged();
                this.OnPropertyChanged("CreatedById");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CreatedById;
        partial void OnCreatedByIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCreatedByIdChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property ModifiedById in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedById")]
        public virtual global::System.Nullable<global::System.Guid> ModifiedById
        {
            get
            {
                return this._ModifiedById;
            }
            set
            {
                this.OnModifiedByIdChanging(value);
                this._ModifiedById = value;
                this.OnModifiedByIdChanged();
                this.OnPropertyChanged("ModifiedById");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ModifiedById;
        partial void OnModifiedByIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnModifiedByIdChanged();
        /// <summary>
        /// There are no comments for Property ProcessListeners in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessListeners")]
        public virtual global::System.Nullable<int> ProcessListeners
        {
            get
            {
                return this._ProcessListeners;
            }
            set
            {
                this.OnProcessListenersChanging(value);
                this._ProcessListeners = value;
                this.OnProcessListenersChanged();
                this.OnPropertyChanged("ProcessListeners");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ProcessListeners;
        partial void OnProcessListenersChanging(global::System.Nullable<int> value);
        partial void OnProcessListenersChanged();
        /// <summary>
        /// There are no comments for Property CampaignId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CampaignId")]
        public virtual global::System.Nullable<global::System.Guid> CampaignId
        {
            get
            {
                return this._CampaignId;
            }
            set
            {
                this.OnCampaignIdChanging(value);
                this._CampaignId = value;
                this.OnCampaignIdChanged();
                this.OnPropertyChanged("CampaignId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CampaignId;
        partial void OnCampaignIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCampaignIdChanged();
        /// <summary>
        /// There are no comments for Property ContactId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactId")]
        public virtual global::System.Nullable<global::System.Guid> ContactId
        {
            get
            {
                return this._ContactId;
            }
            set
            {
                this.OnContactIdChanging(value);
                this._ContactId = value;
                this.OnContactIdChanged();
                this.OnPropertyChanged("ContactId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ContactId;
        partial void OnContactIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnContactIdChanged();
        /// <summary>
        /// There are no comments for Property CampaignTargetStatusId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CampaignTargetStatusId")]
        public virtual global::System.Nullable<global::System.Guid> CampaignTargetStatusId
        {
            get
            {
                return this._CampaignTargetStatusId;
            }
            set
            {
                this.OnCampaignTargetStatusIdChanging(value);
                this._CampaignTargetStatusId = value;
                this.OnCampaignTargetStatusIdChanged();
                this.OnPropertyChanged("CampaignTargetStatusId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CampaignTargetStatusId;
        partial void OnCampaignTargetStatusIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCampaignTargetStatusIdChanged();
        /// <summary>
        /// There are no comments for Property IsFromGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsFromGroup")]
        public virtual global::System.Nullable<bool> IsFromGroup
        {
            get
            {
                return this._IsFromGroup;
            }
            set
            {
                this.OnIsFromGroupChanging(value);
                this._IsFromGroup = value;
                this.OnIsFromGroupChanged();
                this.OnPropertyChanged("IsFromGroup");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _IsFromGroup;
        partial void OnIsFromGroupChanging(global::System.Nullable<bool> value);
        partial void OnIsFromGroupChanged();
        /// <summary>
        /// There are no comments for Property CurrentStepId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrentStepId")]
        public virtual global::System.Nullable<global::System.Guid> CurrentStepId
        {
            get
            {
                return this._CurrentStepId;
            }
            set
            {
                this.OnCurrentStepIdChanging(value);
                this._CurrentStepId = value;
                this.OnCurrentStepIdChanged();
                this.OnPropertyChanged("CurrentStepId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CurrentStepId;
        partial void OnCurrentStepIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCurrentStepIdChanged();
        /// <summary>
        /// There are no comments for Property NextStepId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NextStepId")]
        public virtual global::System.Nullable<global::System.Guid> NextStepId
        {
            get
            {
                return this._NextStepId;
            }
            set
            {
                this.OnNextStepIdChanging(value);
                this._NextStepId = value;
                this.OnNextStepIdChanged();
                this.OnPropertyChanged("NextStepId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _NextStepId;
        partial void OnNextStepIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnNextStepIdChanged();
        /// <summary>
        /// There are no comments for Property PassedStepId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PassedStepId")]
        public virtual global::System.Nullable<global::System.Guid> PassedStepId
        {
            get
            {
                return this._PassedStepId;
            }
            set
            {
                this.OnPassedStepIdChanging(value);
                this._PassedStepId = value;
                this.OnPassedStepIdChanged();
                this.OnPropertyChanged("PassedStepId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _PassedStepId;
        partial void OnPassedStepIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnPassedStepIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedBy")]
        public virtual global::Terrasoft.Configuration.OData.Contact CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.Contact _CreatedBy;
        partial void OnCreatedByChanging(global::Terrasoft.Configuration.OData.Contact value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedBy")]
        public virtual global::Terrasoft.Configuration.OData.Contact ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.Contact _ModifiedBy;
        partial void OnModifiedByChanging(global::Terrasoft.Configuration.OData.Contact value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Campaign in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Campaign")]
        public virtual global::Terrasoft.Configuration.OData.Campaign Campaign
        {
            get
            {
                return this._Campaign;
            }
            set
            {
                this.OnCampaignChanging(value);
                this._Campaign = value;
                this.OnCampaignChanged();
                this.OnPropertyChanged("Campaign");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.Campaign _Campaign;
        partial void OnCampaignChanging(global::Terrasoft.Configuration.OData.Campaign value);
        partial void OnCampaignChanged();
        /// <summary>
        /// There are no comments for Property Contact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Contact")]
        public virtual global::Terrasoft.Configuration.OData.Contact Contact
        {
            get
            {
                return this._Contact;
            }
            set
            {
                this.OnContactChanging(value);
                this._Contact = value;
                this.OnContactChanged();
                this.OnPropertyChanged("Contact");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.Contact _Contact;
        partial void OnContactChanging(global::Terrasoft.Configuration.OData.Contact value);
        partial void OnContactChanged();
        /// <summary>
        /// There are no comments for Property CampaignTargetStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CampaignTargetStatus")]
        public virtual global::Terrasoft.Configuration.OData.CampaignTargetStatus CampaignTargetStatus
        {
            get
            {
                return this._CampaignTargetStatus;
            }
            set
            {
                this.OnCampaignTargetStatusChanging(value);
                this._CampaignTargetStatus = value;
                this.OnCampaignTargetStatusChanged();
                this.OnPropertyChanged("CampaignTargetStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.CampaignTargetStatus _CampaignTargetStatus;
        partial void OnCampaignTargetStatusChanging(global::Terrasoft.Configuration.OData.CampaignTargetStatus value);
        partial void OnCampaignTargetStatusChanged();
        /// <summary>
        /// There are no comments for Property CurrentStep in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrentStep")]
        public virtual global::Terrasoft.Configuration.OData.CampaignStep CurrentStep
        {
            get
            {
                return this._CurrentStep;
            }
            set
            {
                this.OnCurrentStepChanging(value);
                this._CurrentStep = value;
                this.OnCurrentStepChanged();
                this.OnPropertyChanged("CurrentStep");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.CampaignStep _CurrentStep;
        partial void OnCurrentStepChanging(global::Terrasoft.Configuration.OData.CampaignStep value);
        partial void OnCurrentStepChanged();
        /// <summary>
        /// There are no comments for Property NextStep in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NextStep")]
        public virtual global::Terrasoft.Configuration.OData.CampaignStep NextStep
        {
            get
            {
                return this._NextStep;
            }
            set
            {
                this.OnNextStepChanging(value);
                this._NextStep = value;
                this.OnNextStepChanged();
                this.OnPropertyChanged("NextStep");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.CampaignStep _NextStep;
        partial void OnNextStepChanging(global::Terrasoft.Configuration.OData.CampaignStep value);
        partial void OnNextStepChanged();
        /// <summary>
        /// There are no comments for Property PassedStep in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PassedStep")]
        public virtual global::Terrasoft.Configuration.OData.CampaignStep PassedStep
        {
            get
            {
                return this._PassedStep;
            }
            set
            {
                this.OnPassedStepChanging(value);
                this._PassedStep = value;
                this.OnPassedStepChanged();
                this.OnPropertyChanged("PassedStep");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.CampaignStep _PassedStep;
        partial void OnPassedStepChanging(global::Terrasoft.Configuration.OData.CampaignStep value);
        partial void OnPassedStepChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
