//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 09/11/2021 14:00:59
namespace Terrasoft.Configuration.OData
{
    /// <summary>
    /// There are no comments for CountrySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CountrySingle")]
    public partial class CountrySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Country>
    {
        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Country> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedBy")]
        public virtual global::Terrasoft.Configuration.OData.ContactSingle CreatedBy
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CreatedBy == null))
                {
                    this._CreatedBy = new global::Terrasoft.Configuration.OData.ContactSingle(this.Context, GetPath("CreatedBy"));
                }
                return this._CreatedBy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ContactSingle _CreatedBy;
        /// <summary>
        /// There are no comments for ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedBy")]
        public virtual global::Terrasoft.Configuration.OData.ContactSingle ModifiedBy
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ModifiedBy == null))
                {
                    this._ModifiedBy = new global::Terrasoft.Configuration.OData.ContactSingle(this.Context, GetPath("ModifiedBy"));
                }
                return this._ModifiedBy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ContactSingle _ModifiedBy;
        /// <summary>
        /// There are no comments for TimeZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TimeZone")]
        public virtual global::Terrasoft.Configuration.OData.TimeZoneSingle TimeZone
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._TimeZone == null))
                {
                    this._TimeZone = new global::Terrasoft.Configuration.OData.TimeZoneSingle(this.Context, GetPath("TimeZone"));
                }
                return this._TimeZone;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.TimeZoneSingle _TimeZone;
        /// <summary>
        /// There are no comments for AccountOwnershipCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AccountOwnershipCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.AccountOwnership> AccountOwnershipCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._AccountOwnershipCollectionByCountry == null))
                {
                    this._AccountOwnershipCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.AccountOwnership>(GetPath("AccountOwnershipCollectionByCountry"));
                }
                return this._AccountOwnershipCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.AccountOwnership> _AccountOwnershipCollectionByCountry;
        /// <summary>
        /// There are no comments for CityCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CityCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.City> CityCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CityCollectionByCountry == null))
                {
                    this._CityCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.City>(GetPath("CityCollectionByCountry"));
                }
                return this._CityCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.City> _CityCollectionByCountry;
        /// <summary>
        /// There are no comments for RegionCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RegionCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Region> RegionCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._RegionCollectionByCountry == null))
                {
                    this._RegionCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.Region>(GetPath("RegionCollectionByCountry"));
                }
                return this._RegionCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Region> _RegionCollectionByCountry;
        /// <summary>
        /// There are no comments for AccountCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AccountCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Account> AccountCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._AccountCollectionByCountry == null))
                {
                    this._AccountCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.Account>(GetPath("AccountCollectionByCountry"));
                }
                return this._AccountCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Account> _AccountCollectionByCountry;
        /// <summary>
        /// There are no comments for ContactCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Contact> ContactCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ContactCollectionByCountry == null))
                {
                    this._ContactCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.Contact>(GetPath("ContactCollectionByCountry"));
                }
                return this._ContactCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Contact> _ContactCollectionByCountry;
        /// <summary>
        /// There are no comments for AccountAddressCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AccountAddressCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.AccountAddress> AccountAddressCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._AccountAddressCollectionByCountry == null))
                {
                    this._AccountAddressCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.AccountAddress>(GetPath("AccountAddressCollectionByCountry"));
                }
                return this._AccountAddressCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.AccountAddress> _AccountAddressCollectionByCountry;
        /// <summary>
        /// There are no comments for AccountBillingInfoCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AccountBillingInfoCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.AccountBillingInfo> AccountBillingInfoCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._AccountBillingInfoCollectionByCountry == null))
                {
                    this._AccountBillingInfoCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.AccountBillingInfo>(GetPath("AccountBillingInfoCollectionByCountry"));
                }
                return this._AccountBillingInfoCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.AccountBillingInfo> _AccountBillingInfoCollectionByCountry;
        /// <summary>
        /// There are no comments for LeadCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LeadCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Lead> LeadCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LeadCollectionByCountry == null))
                {
                    this._LeadCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.Lead>(GetPath("LeadCollectionByCountry"));
                }
                return this._LeadCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Lead> _LeadCollectionByCountry;
        /// <summary>
        /// There are no comments for ConfItemCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ConfItemCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ConfItem> ConfItemCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ConfItemCollectionByCountry == null))
                {
                    this._ConfItemCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.ConfItem>(GetPath("ConfItemCollectionByCountry"));
                }
                return this._ConfItemCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ConfItem> _ConfItemCollectionByCountry;
        /// <summary>
        /// There are no comments for ConfItemAddressCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ConfItemAddressCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ConfItemAddress> ConfItemAddressCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ConfItemAddressCollectionByCountry == null))
                {
                    this._ConfItemAddressCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.ConfItemAddress>(GetPath("ConfItemAddressCollectionByCountry"));
                }
                return this._ConfItemAddressCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ConfItemAddress> _ConfItemAddressCollectionByCountry;
        /// <summary>
        /// There are no comments for ContactAddressCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactAddressCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ContactAddress> ContactAddressCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ContactAddressCollectionByCountry == null))
                {
                    this._ContactAddressCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.ContactAddress>(GetPath("ContactAddressCollectionByCountry"));
                }
                return this._ContactAddressCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ContactAddress> _ContactAddressCollectionByCountry;
        /// <summary>
        /// There are no comments for DialingCodeCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DialingCodeCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.DialingCode> DialingCodeCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._DialingCodeCollectionByCountry == null))
                {
                    this._DialingCodeCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.DialingCode>(GetPath("DialingCodeCollectionByCountry"));
                }
                return this._DialingCodeCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.DialingCode> _DialingCodeCollectionByCountry;
        /// <summary>
        /// There are no comments for FormSubmitCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FormSubmitCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.FormSubmit> FormSubmitCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._FormSubmitCollectionByCountry == null))
                {
                    this._FormSubmitCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.FormSubmit>(GetPath("FormSubmitCollectionByCountry"));
                }
                return this._FormSubmitCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.FormSubmit> _FormSubmitCollectionByCountry;
        /// <summary>
        /// There are no comments for LeadAddressCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LeadAddressCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.LeadAddress> LeadAddressCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LeadAddressCollectionByCountry == null))
                {
                    this._LeadAddressCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.LeadAddress>(GetPath("LeadAddressCollectionByCountry"));
                }
                return this._LeadAddressCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.LeadAddress> _LeadAddressCollectionByCountry;
        /// <summary>
        /// There are no comments for LeadQualificationCollectionByLeadContactCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LeadQualificationCollectionByLeadContactCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.LeadQualification> LeadQualificationCollectionByLeadContactCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LeadQualificationCollectionByLeadContactCountry == null))
                {
                    this._LeadQualificationCollectionByLeadContactCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.LeadQualification>(GetPath("LeadQualificationCollectionByLeadContactCountry"));
                }
                return this._LeadQualificationCollectionByLeadContactCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.LeadQualification> _LeadQualificationCollectionByLeadContactCountry;
        /// <summary>
        /// There are no comments for LeadQualificationCollectionByLeadAccountCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LeadQualificationCollectionByLeadAccountCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.LeadQualification> LeadQualificationCollectionByLeadAccountCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LeadQualificationCollectionByLeadAccountCountry == null))
                {
                    this._LeadQualificationCollectionByLeadAccountCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.LeadQualification>(GetPath("LeadQualificationCollectionByLeadAccountCountry"));
                }
                return this._LeadQualificationCollectionByLeadAccountCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.LeadQualification> _LeadQualificationCollectionByLeadAccountCountry;
        /// <summary>
        /// There are no comments for TouchCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TouchCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Touch> TouchCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._TouchCollectionByCountry == null))
                {
                    this._TouchCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.Touch>(GetPath("TouchCollectionByCountry"));
                }
                return this._TouchCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Touch> _TouchCollectionByCountry;
        /// <summary>
        /// There are no comments for VwClientAddressCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VwClientAddressCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.VwClientAddress> VwClientAddressCollectionByCountry
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._VwClientAddressCollectionByCountry == null))
                {
                    this._VwClientAddressCollectionByCountry = Context.CreateQuery<global::Terrasoft.Configuration.OData.VwClientAddress>(GetPath("VwClientAddressCollectionByCountry"));
                }
                return this._VwClientAddressCollectionByCountry;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.VwClientAddress> _VwClientAddressCollectionByCountry;
    }
    /// <summary>
    /// There are no comments for Country in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.EntitySet("Country")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Country")]
    public partial class Country : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Country object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="image">Initial value of Image.</param>
        /// <param name="billingInfo">Initial value of BillingInfo.</param>
        /// <param name="code">Initial value of Code.</param>
        /// <param name="alpha2Code">Initial value of Alpha2Code.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Country CreateCountry(string name, 
                    string description, 
                    global::Microsoft.OData.Client.DataServiceStreamLink image, 
                    string billingInfo, 
                    string code, 
                    string alpha2Code)
        {
            Country country = new Country();
            country.Name = name;
            country.Description = description;
            country.Image = image;
            country.BillingInfo = billingInfo;
            country.Code = code;
            country.Alpha2Code = alpha2Code;
            return country;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public virtual global::System.Nullable<global::System.Guid> Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _Id;
        partial void OnIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property CreatedById in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedById")]
        public virtual global::System.Nullable<global::System.Guid> CreatedById
        {
            get
            {
                return this._CreatedById;
            }
            set
            {
                this.OnCreatedByIdChanging(value);
                this._CreatedById = value;
                this.OnCreatedByIdChanged();
                this.OnPropertyChanged("CreatedById");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CreatedById;
        partial void OnCreatedByIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCreatedByIdChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property ModifiedById in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedById")]
        public virtual global::System.Nullable<global::System.Guid> ModifiedById
        {
            get
            {
                return this._ModifiedById;
            }
            set
            {
                this.OnModifiedByIdChanging(value);
                this._ModifiedById = value;
                this.OnModifiedByIdChanged();
                this.OnPropertyChanged("ModifiedById");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ModifiedById;
        partial void OnModifiedByIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnModifiedByIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Name is required.")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Description is required.")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Image")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Image is required.")]
        public virtual global::Microsoft.OData.Client.DataServiceStreamLink Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this._Image = value;
                this.OnImageChanged();
                this.OnPropertyChanged("Image");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceStreamLink _Image;
        partial void OnImageChanging(global::Microsoft.OData.Client.DataServiceStreamLink value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property BillingInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillingInfo")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BillingInfo is required.")]
        public virtual string BillingInfo
        {
            get
            {
                return this._BillingInfo;
            }
            set
            {
                this.OnBillingInfoChanging(value);
                this._BillingInfo = value;
                this.OnBillingInfoChanged();
                this.OnPropertyChanged("BillingInfo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillingInfo;
        partial void OnBillingInfoChanging(string value);
        partial void OnBillingInfoChanged();
        /// <summary>
        /// There are no comments for Property ProcessListeners in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessListeners")]
        public virtual global::System.Nullable<int> ProcessListeners
        {
            get
            {
                return this._ProcessListeners;
            }
            set
            {
                this.OnProcessListenersChanging(value);
                this._ProcessListeners = value;
                this.OnProcessListenersChanged();
                this.OnPropertyChanged("ProcessListeners");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ProcessListeners;
        partial void OnProcessListenersChanging(global::System.Nullable<int> value);
        partial void OnProcessListenersChanged();
        /// <summary>
        /// There are no comments for Property TimeZoneId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TimeZoneId")]
        public virtual global::System.Nullable<global::System.Guid> TimeZoneId
        {
            get
            {
                return this._TimeZoneId;
            }
            set
            {
                this.OnTimeZoneIdChanging(value);
                this._TimeZoneId = value;
                this.OnTimeZoneIdChanged();
                this.OnPropertyChanged("TimeZoneId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _TimeZoneId;
        partial void OnTimeZoneIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnTimeZoneIdChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Code")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Code is required.")]
        public virtual string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Alpha2Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Alpha2Code")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Alpha2Code is required.")]
        public virtual string Alpha2Code
        {
            get
            {
                return this._Alpha2Code;
            }
            set
            {
                this.OnAlpha2CodeChanging(value);
                this._Alpha2Code = value;
                this.OnAlpha2CodeChanged();
                this.OnPropertyChanged("Alpha2Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Alpha2Code;
        partial void OnAlpha2CodeChanging(string value);
        partial void OnAlpha2CodeChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedBy")]
        public virtual global::Terrasoft.Configuration.OData.Contact CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.Contact _CreatedBy;
        partial void OnCreatedByChanging(global::Terrasoft.Configuration.OData.Contact value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedBy")]
        public virtual global::Terrasoft.Configuration.OData.Contact ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.Contact _ModifiedBy;
        partial void OnModifiedByChanging(global::Terrasoft.Configuration.OData.Contact value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property TimeZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TimeZone")]
        public virtual global::Terrasoft.Configuration.OData.TimeZone TimeZone
        {
            get
            {
                return this._TimeZone;
            }
            set
            {
                this.OnTimeZoneChanging(value);
                this._TimeZone = value;
                this.OnTimeZoneChanged();
                this.OnPropertyChanged("TimeZone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.TimeZone _TimeZone;
        partial void OnTimeZoneChanging(global::Terrasoft.Configuration.OData.TimeZone value);
        partial void OnTimeZoneChanged();
        /// <summary>
        /// There are no comments for Property AccountOwnershipCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AccountOwnershipCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountOwnership> AccountOwnershipCollectionByCountry
        {
            get
            {
                return this._AccountOwnershipCollectionByCountry;
            }
            set
            {
                this.OnAccountOwnershipCollectionByCountryChanging(value);
                this._AccountOwnershipCollectionByCountry = value;
                this.OnAccountOwnershipCollectionByCountryChanged();
                this.OnPropertyChanged("AccountOwnershipCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountOwnership> _AccountOwnershipCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountOwnership>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnAccountOwnershipCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountOwnership> value);
        partial void OnAccountOwnershipCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property CityCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CityCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.City> CityCollectionByCountry
        {
            get
            {
                return this._CityCollectionByCountry;
            }
            set
            {
                this.OnCityCollectionByCountryChanging(value);
                this._CityCollectionByCountry = value;
                this.OnCityCollectionByCountryChanged();
                this.OnPropertyChanged("CityCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.City> _CityCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.City>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCityCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.City> value);
        partial void OnCityCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property RegionCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RegionCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Region> RegionCollectionByCountry
        {
            get
            {
                return this._RegionCollectionByCountry;
            }
            set
            {
                this.OnRegionCollectionByCountryChanging(value);
                this._RegionCollectionByCountry = value;
                this.OnRegionCollectionByCountryChanged();
                this.OnPropertyChanged("RegionCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Region> _RegionCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Region>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnRegionCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Region> value);
        partial void OnRegionCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property AccountCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AccountCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Account> AccountCollectionByCountry
        {
            get
            {
                return this._AccountCollectionByCountry;
            }
            set
            {
                this.OnAccountCollectionByCountryChanging(value);
                this._AccountCollectionByCountry = value;
                this.OnAccountCollectionByCountryChanged();
                this.OnPropertyChanged("AccountCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Account> _AccountCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Account>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnAccountCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Account> value);
        partial void OnAccountCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property ContactCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Contact> ContactCollectionByCountry
        {
            get
            {
                return this._ContactCollectionByCountry;
            }
            set
            {
                this.OnContactCollectionByCountryChanging(value);
                this._ContactCollectionByCountry = value;
                this.OnContactCollectionByCountryChanged();
                this.OnPropertyChanged("ContactCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Contact> _ContactCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Contact>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnContactCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Contact> value);
        partial void OnContactCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property AccountAddressCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AccountAddressCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountAddress> AccountAddressCollectionByCountry
        {
            get
            {
                return this._AccountAddressCollectionByCountry;
            }
            set
            {
                this.OnAccountAddressCollectionByCountryChanging(value);
                this._AccountAddressCollectionByCountry = value;
                this.OnAccountAddressCollectionByCountryChanged();
                this.OnPropertyChanged("AccountAddressCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountAddress> _AccountAddressCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountAddress>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnAccountAddressCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountAddress> value);
        partial void OnAccountAddressCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property AccountBillingInfoCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AccountBillingInfoCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountBillingInfo> AccountBillingInfoCollectionByCountry
        {
            get
            {
                return this._AccountBillingInfoCollectionByCountry;
            }
            set
            {
                this.OnAccountBillingInfoCollectionByCountryChanging(value);
                this._AccountBillingInfoCollectionByCountry = value;
                this.OnAccountBillingInfoCollectionByCountryChanged();
                this.OnPropertyChanged("AccountBillingInfoCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountBillingInfo> _AccountBillingInfoCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountBillingInfo>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnAccountBillingInfoCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.AccountBillingInfo> value);
        partial void OnAccountBillingInfoCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property LeadCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LeadCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Lead> LeadCollectionByCountry
        {
            get
            {
                return this._LeadCollectionByCountry;
            }
            set
            {
                this.OnLeadCollectionByCountryChanging(value);
                this._LeadCollectionByCountry = value;
                this.OnLeadCollectionByCountryChanged();
                this.OnPropertyChanged("LeadCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Lead> _LeadCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Lead>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnLeadCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Lead> value);
        partial void OnLeadCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property ConfItemCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConfItemCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ConfItem> ConfItemCollectionByCountry
        {
            get
            {
                return this._ConfItemCollectionByCountry;
            }
            set
            {
                this.OnConfItemCollectionByCountryChanging(value);
                this._ConfItemCollectionByCountry = value;
                this.OnConfItemCollectionByCountryChanged();
                this.OnPropertyChanged("ConfItemCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ConfItem> _ConfItemCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ConfItem>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnConfItemCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ConfItem> value);
        partial void OnConfItemCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property ConfItemAddressCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConfItemAddressCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ConfItemAddress> ConfItemAddressCollectionByCountry
        {
            get
            {
                return this._ConfItemAddressCollectionByCountry;
            }
            set
            {
                this.OnConfItemAddressCollectionByCountryChanging(value);
                this._ConfItemAddressCollectionByCountry = value;
                this.OnConfItemAddressCollectionByCountryChanged();
                this.OnPropertyChanged("ConfItemAddressCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ConfItemAddress> _ConfItemAddressCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ConfItemAddress>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnConfItemAddressCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ConfItemAddress> value);
        partial void OnConfItemAddressCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property ContactAddressCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactAddressCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ContactAddress> ContactAddressCollectionByCountry
        {
            get
            {
                return this._ContactAddressCollectionByCountry;
            }
            set
            {
                this.OnContactAddressCollectionByCountryChanging(value);
                this._ContactAddressCollectionByCountry = value;
                this.OnContactAddressCollectionByCountryChanged();
                this.OnPropertyChanged("ContactAddressCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ContactAddress> _ContactAddressCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ContactAddress>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnContactAddressCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ContactAddress> value);
        partial void OnContactAddressCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property DialingCodeCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DialingCodeCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.DialingCode> DialingCodeCollectionByCountry
        {
            get
            {
                return this._DialingCodeCollectionByCountry;
            }
            set
            {
                this.OnDialingCodeCollectionByCountryChanging(value);
                this._DialingCodeCollectionByCountry = value;
                this.OnDialingCodeCollectionByCountryChanged();
                this.OnPropertyChanged("DialingCodeCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.DialingCode> _DialingCodeCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.DialingCode>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnDialingCodeCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.DialingCode> value);
        partial void OnDialingCodeCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property FormSubmitCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FormSubmitCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.FormSubmit> FormSubmitCollectionByCountry
        {
            get
            {
                return this._FormSubmitCollectionByCountry;
            }
            set
            {
                this.OnFormSubmitCollectionByCountryChanging(value);
                this._FormSubmitCollectionByCountry = value;
                this.OnFormSubmitCollectionByCountryChanged();
                this.OnPropertyChanged("FormSubmitCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.FormSubmit> _FormSubmitCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.FormSubmit>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnFormSubmitCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.FormSubmit> value);
        partial void OnFormSubmitCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property LeadAddressCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LeadAddressCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadAddress> LeadAddressCollectionByCountry
        {
            get
            {
                return this._LeadAddressCollectionByCountry;
            }
            set
            {
                this.OnLeadAddressCollectionByCountryChanging(value);
                this._LeadAddressCollectionByCountry = value;
                this.OnLeadAddressCollectionByCountryChanged();
                this.OnPropertyChanged("LeadAddressCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadAddress> _LeadAddressCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadAddress>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnLeadAddressCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadAddress> value);
        partial void OnLeadAddressCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property LeadQualificationCollectionByLeadContactCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LeadQualificationCollectionByLeadContactCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadQualification> LeadQualificationCollectionByLeadContactCountry
        {
            get
            {
                return this._LeadQualificationCollectionByLeadContactCountry;
            }
            set
            {
                this.OnLeadQualificationCollectionByLeadContactCountryChanging(value);
                this._LeadQualificationCollectionByLeadContactCountry = value;
                this.OnLeadQualificationCollectionByLeadContactCountryChanged();
                this.OnPropertyChanged("LeadQualificationCollectionByLeadContactCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadQualification> _LeadQualificationCollectionByLeadContactCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadQualification>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnLeadQualificationCollectionByLeadContactCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadQualification> value);
        partial void OnLeadQualificationCollectionByLeadContactCountryChanged();
        /// <summary>
        /// There are no comments for Property LeadQualificationCollectionByLeadAccountCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LeadQualificationCollectionByLeadAccountCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadQualification> LeadQualificationCollectionByLeadAccountCountry
        {
            get
            {
                return this._LeadQualificationCollectionByLeadAccountCountry;
            }
            set
            {
                this.OnLeadQualificationCollectionByLeadAccountCountryChanging(value);
                this._LeadQualificationCollectionByLeadAccountCountry = value;
                this.OnLeadQualificationCollectionByLeadAccountCountryChanged();
                this.OnPropertyChanged("LeadQualificationCollectionByLeadAccountCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadQualification> _LeadQualificationCollectionByLeadAccountCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadQualification>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnLeadQualificationCollectionByLeadAccountCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.LeadQualification> value);
        partial void OnLeadQualificationCollectionByLeadAccountCountryChanged();
        /// <summary>
        /// There are no comments for Property TouchCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TouchCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Touch> TouchCollectionByCountry
        {
            get
            {
                return this._TouchCollectionByCountry;
            }
            set
            {
                this.OnTouchCollectionByCountryChanging(value);
                this._TouchCollectionByCountry = value;
                this.OnTouchCollectionByCountryChanged();
                this.OnPropertyChanged("TouchCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Touch> _TouchCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Touch>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnTouchCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Touch> value);
        partial void OnTouchCollectionByCountryChanged();
        /// <summary>
        /// There are no comments for Property VwClientAddressCollectionByCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("VwClientAddressCollectionByCountry")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.VwClientAddress> VwClientAddressCollectionByCountry
        {
            get
            {
                return this._VwClientAddressCollectionByCountry;
            }
            set
            {
                this.OnVwClientAddressCollectionByCountryChanging(value);
                this._VwClientAddressCollectionByCountry = value;
                this.OnVwClientAddressCollectionByCountryChanged();
                this.OnPropertyChanged("VwClientAddressCollectionByCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.VwClientAddress> _VwClientAddressCollectionByCountry = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.VwClientAddress>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnVwClientAddressCollectionByCountryChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.VwClientAddress> value);
        partial void OnVwClientAddressCollectionByCountryChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
