//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 09/11/2021 14:00:59
namespace Terrasoft.Configuration.OData
{
    /// <summary>
    /// There are no comments for ReleaseSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseSingle")]
    public partial class ReleaseSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Release>
    {
        /// <summary>
        /// Initialize a new ReleaseSingle object.
        /// </summary>
        public ReleaseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ReleaseSingle object.
        /// </summary>
        public ReleaseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ReleaseSingle object.
        /// </summary>
        public ReleaseSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Release> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedBy")]
        public virtual global::Terrasoft.Configuration.OData.ContactSingle CreatedBy
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CreatedBy == null))
                {
                    this._CreatedBy = new global::Terrasoft.Configuration.OData.ContactSingle(this.Context, GetPath("CreatedBy"));
                }
                return this._CreatedBy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ContactSingle _CreatedBy;
        /// <summary>
        /// There are no comments for ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedBy")]
        public virtual global::Terrasoft.Configuration.OData.ContactSingle ModifiedBy
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ModifiedBy == null))
                {
                    this._ModifiedBy = new global::Terrasoft.Configuration.OData.ContactSingle(this.Context, GetPath("ModifiedBy"));
                }
                return this._ModifiedBy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ContactSingle _ModifiedBy;
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public virtual global::Terrasoft.Configuration.OData.ReleaseStatusSingle Status
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Status == null))
                {
                    this._Status = new global::Terrasoft.Configuration.OData.ReleaseStatusSingle(this.Context, GetPath("Status"));
                }
                return this._Status;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ReleaseStatusSingle _Status;
        /// <summary>
        /// There are no comments for Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Type")]
        public virtual global::Terrasoft.Configuration.OData.ReleaseTypeSingle Type
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Type == null))
                {
                    this._Type = new global::Terrasoft.Configuration.OData.ReleaseTypeSingle(this.Context, GetPath("Type"));
                }
                return this._Type;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ReleaseTypeSingle _Type;
        /// <summary>
        /// There are no comments for Priority in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Priority")]
        public virtual global::Terrasoft.Configuration.OData.ReleasePrioritySingle Priority
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Priority == null))
                {
                    this._Priority = new global::Terrasoft.Configuration.OData.ReleasePrioritySingle(this.Context, GetPath("Priority"));
                }
                return this._Priority;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ReleasePrioritySingle _Priority;
        /// <summary>
        /// There are no comments for ChangeCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ChangeCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Change> ChangeCollectionByRelease
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ChangeCollectionByRelease == null))
                {
                    this._ChangeCollectionByRelease = Context.CreateQuery<global::Terrasoft.Configuration.OData.Change>(GetPath("ChangeCollectionByRelease"));
                }
                return this._ChangeCollectionByRelease;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Change> _ChangeCollectionByRelease;
        /// <summary>
        /// There are no comments for ActivityCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ActivityCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Activity> ActivityCollectionByRelease
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ActivityCollectionByRelease == null))
                {
                    this._ActivityCollectionByRelease = Context.CreateQuery<global::Terrasoft.Configuration.OData.Activity>(GetPath("ActivityCollectionByRelease"));
                }
                return this._ActivityCollectionByRelease;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.Activity> _ActivityCollectionByRelease;
        /// <summary>
        /// There are no comments for ReleaseConfItemCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseConfItemCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseConfItem> ReleaseConfItemCollectionByRelease
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ReleaseConfItemCollectionByRelease == null))
                {
                    this._ReleaseConfItemCollectionByRelease = Context.CreateQuery<global::Terrasoft.Configuration.OData.ReleaseConfItem>(GetPath("ReleaseConfItemCollectionByRelease"));
                }
                return this._ReleaseConfItemCollectionByRelease;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseConfItem> _ReleaseConfItemCollectionByRelease;
        /// <summary>
        /// There are no comments for ReleaseFileCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseFileCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseFile> ReleaseFileCollectionByRelease
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ReleaseFileCollectionByRelease == null))
                {
                    this._ReleaseFileCollectionByRelease = Context.CreateQuery<global::Terrasoft.Configuration.OData.ReleaseFile>(GetPath("ReleaseFileCollectionByRelease"));
                }
                return this._ReleaseFileCollectionByRelease;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseFile> _ReleaseFileCollectionByRelease;
        /// <summary>
        /// There are no comments for ReleaseInFolderCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseInFolderCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseInFolder> ReleaseInFolderCollectionByRelease
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ReleaseInFolderCollectionByRelease == null))
                {
                    this._ReleaseInFolderCollectionByRelease = Context.CreateQuery<global::Terrasoft.Configuration.OData.ReleaseInFolder>(GetPath("ReleaseInFolderCollectionByRelease"));
                }
                return this._ReleaseInFolderCollectionByRelease;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseInFolder> _ReleaseInFolderCollectionByRelease;
        /// <summary>
        /// There are no comments for ReleaseInTagCollectionByEntity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseInTagCollectionByEntity")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseInTag> ReleaseInTagCollectionByEntity
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ReleaseInTagCollectionByEntity == null))
                {
                    this._ReleaseInTagCollectionByEntity = Context.CreateQuery<global::Terrasoft.Configuration.OData.ReleaseInTag>(GetPath("ReleaseInTagCollectionByEntity"));
                }
                return this._ReleaseInTagCollectionByEntity;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseInTag> _ReleaseInTagCollectionByEntity;
        /// <summary>
        /// There are no comments for ReleaseServiceItemCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseServiceItemCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseServiceItem> ReleaseServiceItemCollectionByRelease
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ReleaseServiceItemCollectionByRelease == null))
                {
                    this._ReleaseServiceItemCollectionByRelease = Context.CreateQuery<global::Terrasoft.Configuration.OData.ReleaseServiceItem>(GetPath("ReleaseServiceItemCollectionByRelease"));
                }
                return this._ReleaseServiceItemCollectionByRelease;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseServiceItem> _ReleaseServiceItemCollectionByRelease;
        /// <summary>
        /// There are no comments for ReleaseTeamCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseTeamCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseTeam> ReleaseTeamCollectionByRelease
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ReleaseTeamCollectionByRelease == null))
                {
                    this._ReleaseTeamCollectionByRelease = Context.CreateQuery<global::Terrasoft.Configuration.OData.ReleaseTeam>(GetPath("ReleaseTeamCollectionByRelease"));
                }
                return this._ReleaseTeamCollectionByRelease;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ReleaseTeam> _ReleaseTeamCollectionByRelease;
        /// <summary>
        /// There are no comments for ScheduledDateCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ScheduledDateCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ScheduledDate> ScheduledDateCollectionByRelease
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ScheduledDateCollectionByRelease == null))
                {
                    this._ScheduledDateCollectionByRelease = Context.CreateQuery<global::Terrasoft.Configuration.OData.ScheduledDate>(GetPath("ScheduledDateCollectionByRelease"));
                }
                return this._ScheduledDateCollectionByRelease;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Terrasoft.Configuration.OData.ScheduledDate> _ScheduledDateCollectionByRelease;
    }
    /// <summary>
    /// There are no comments for Release in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.EntitySet("Release")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Release")]
    public partial class Release : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Release object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="number">Initial value of Number.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="notes">Initial value of Notes.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Release CreateRelease(string name, string number, string description, string notes)
        {
            Release release = new Release();
            release.Name = name;
            release.Number = number;
            release.Description = description;
            release.Notes = notes;
            return release;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public virtual global::System.Nullable<global::System.Guid> Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _Id;
        partial void OnIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property CreatedById in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedById")]
        public virtual global::System.Nullable<global::System.Guid> CreatedById
        {
            get
            {
                return this._CreatedById;
            }
            set
            {
                this.OnCreatedByIdChanging(value);
                this._CreatedById = value;
                this.OnCreatedByIdChanged();
                this.OnPropertyChanged("CreatedById");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CreatedById;
        partial void OnCreatedByIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCreatedByIdChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property ModifiedById in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedById")]
        public virtual global::System.Nullable<global::System.Guid> ModifiedById
        {
            get
            {
                return this._ModifiedById;
            }
            set
            {
                this.OnModifiedByIdChanging(value);
                this._ModifiedById = value;
                this.OnModifiedByIdChanged();
                this.OnPropertyChanged("ModifiedById");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ModifiedById;
        partial void OnModifiedByIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnModifiedByIdChanged();
        /// <summary>
        /// There are no comments for Property ProcessListeners in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessListeners")]
        public virtual global::System.Nullable<int> ProcessListeners
        {
            get
            {
                return this._ProcessListeners;
            }
            set
            {
                this.OnProcessListenersChanging(value);
                this._ProcessListeners = value;
                this.OnProcessListenersChanged();
                this.OnPropertyChanged("ProcessListeners");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ProcessListeners;
        partial void OnProcessListenersChanging(global::System.Nullable<int> value);
        partial void OnProcessListenersChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Name is required.")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Number")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Number is required.")]
        public virtual string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Description is required.")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ScheduledReleaseDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ScheduledReleaseDate")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ScheduledReleaseDate
        {
            get
            {
                return this._ScheduledReleaseDate;
            }
            set
            {
                this.OnScheduledReleaseDateChanging(value);
                this._ScheduledReleaseDate = value;
                this.OnScheduledReleaseDateChanged();
                this.OnPropertyChanged("ScheduledReleaseDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ScheduledReleaseDate;
        partial void OnScheduledReleaseDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnScheduledReleaseDateChanged();
        /// <summary>
        /// There are no comments for Property PlannedLabor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PlannedLabor")]
        public virtual global::System.Nullable<int> PlannedLabor
        {
            get
            {
                return this._PlannedLabor;
            }
            set
            {
                this.OnPlannedLaborChanging(value);
                this._PlannedLabor = value;
                this.OnPlannedLaborChanged();
                this.OnPropertyChanged("PlannedLabor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _PlannedLabor;
        partial void OnPlannedLaborChanging(global::System.Nullable<int> value);
        partial void OnPlannedLaborChanged();
        /// <summary>
        /// There are no comments for Property ReleasedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleasedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ReleasedOn
        {
            get
            {
                return this._ReleasedOn;
            }
            set
            {
                this.OnReleasedOnChanging(value);
                this._ReleasedOn = value;
                this.OnReleasedOnChanged();
                this.OnPropertyChanged("ReleasedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ReleasedOn;
        partial void OnReleasedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnReleasedOnChanged();
        /// <summary>
        /// There are no comments for Property DevelopmentFinishedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DevelopmentFinishedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> DevelopmentFinishedOn
        {
            get
            {
                return this._DevelopmentFinishedOn;
            }
            set
            {
                this.OnDevelopmentFinishedOnChanging(value);
                this._DevelopmentFinishedOn = value;
                this.OnDevelopmentFinishedOnChanged();
                this.OnPropertyChanged("DevelopmentFinishedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _DevelopmentFinishedOn;
        partial void OnDevelopmentFinishedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDevelopmentFinishedOnChanged();
        /// <summary>
        /// There are no comments for Property TestingFinishedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TestingFinishedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> TestingFinishedOn
        {
            get
            {
                return this._TestingFinishedOn;
            }
            set
            {
                this.OnTestingFinishedOnChanging(value);
                this._TestingFinishedOn = value;
                this.OnTestingFinishedOnChanged();
                this.OnPropertyChanged("TestingFinishedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _TestingFinishedOn;
        partial void OnTestingFinishedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnTestingFinishedOnChanged();
        /// <summary>
        /// There are no comments for Property DeploymentFinishedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeploymentFinishedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> DeploymentFinishedOn
        {
            get
            {
                return this._DeploymentFinishedOn;
            }
            set
            {
                this.OnDeploymentFinishedOnChanging(value);
                this._DeploymentFinishedOn = value;
                this.OnDeploymentFinishedOnChanged();
                this.OnPropertyChanged("DeploymentFinishedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _DeploymentFinishedOn;
        partial void OnDeploymentFinishedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDeploymentFinishedOnChanged();
        /// <summary>
        /// There are no comments for Property ActualLabor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ActualLabor")]
        public virtual global::System.Nullable<int> ActualLabor
        {
            get
            {
                return this._ActualLabor;
            }
            set
            {
                this.OnActualLaborChanging(value);
                this._ActualLabor = value;
                this.OnActualLaborChanged();
                this.OnPropertyChanged("ActualLabor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ActualLabor;
        partial void OnActualLaborChanging(global::System.Nullable<int> value);
        partial void OnActualLaborChanged();
        /// <summary>
        /// There are no comments for Property ActualDevelopmentLabor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ActualDevelopmentLabor")]
        public virtual global::System.Nullable<int> ActualDevelopmentLabor
        {
            get
            {
                return this._ActualDevelopmentLabor;
            }
            set
            {
                this.OnActualDevelopmentLaborChanging(value);
                this._ActualDevelopmentLabor = value;
                this.OnActualDevelopmentLaborChanged();
                this.OnPropertyChanged("ActualDevelopmentLabor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ActualDevelopmentLabor;
        partial void OnActualDevelopmentLaborChanging(global::System.Nullable<int> value);
        partial void OnActualDevelopmentLaborChanged();
        /// <summary>
        /// There are no comments for Property ActualTestingLabor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ActualTestingLabor")]
        public virtual global::System.Nullable<int> ActualTestingLabor
        {
            get
            {
                return this._ActualTestingLabor;
            }
            set
            {
                this.OnActualTestingLaborChanging(value);
                this._ActualTestingLabor = value;
                this.OnActualTestingLaborChanged();
                this.OnPropertyChanged("ActualTestingLabor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ActualTestingLabor;
        partial void OnActualTestingLaborChanging(global::System.Nullable<int> value);
        partial void OnActualTestingLaborChanged();
        /// <summary>
        /// There are no comments for Property ActualDeploymentLabor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ActualDeploymentLabor")]
        public virtual global::System.Nullable<int> ActualDeploymentLabor
        {
            get
            {
                return this._ActualDeploymentLabor;
            }
            set
            {
                this.OnActualDeploymentLaborChanging(value);
                this._ActualDeploymentLabor = value;
                this.OnActualDeploymentLaborChanged();
                this.OnPropertyChanged("ActualDeploymentLabor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ActualDeploymentLabor;
        partial void OnActualDeploymentLaborChanging(global::System.Nullable<int> value);
        partial void OnActualDeploymentLaborChanged();
        /// <summary>
        /// There are no comments for Property StatusId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("StatusId")]
        public virtual global::System.Nullable<global::System.Guid> StatusId
        {
            get
            {
                return this._StatusId;
            }
            set
            {
                this.OnStatusIdChanging(value);
                this._StatusId = value;
                this.OnStatusIdChanged();
                this.OnPropertyChanged("StatusId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _StatusId;
        partial void OnStatusIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnStatusIdChanged();
        /// <summary>
        /// There are no comments for Property TypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TypeId")]
        public virtual global::System.Nullable<global::System.Guid> TypeId
        {
            get
            {
                return this._TypeId;
            }
            set
            {
                this.OnTypeIdChanging(value);
                this._TypeId = value;
                this.OnTypeIdChanged();
                this.OnPropertyChanged("TypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _TypeId;
        partial void OnTypeIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnTypeIdChanged();
        /// <summary>
        /// There are no comments for Property PriorityId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PriorityId")]
        public virtual global::System.Nullable<global::System.Guid> PriorityId
        {
            get
            {
                return this._PriorityId;
            }
            set
            {
                this.OnPriorityIdChanging(value);
                this._PriorityId = value;
                this.OnPriorityIdChanged();
                this.OnPropertyChanged("PriorityId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _PriorityId;
        partial void OnPriorityIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnPriorityIdChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Notes")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Notes is required.")]
        public virtual string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedBy")]
        public virtual global::Terrasoft.Configuration.OData.Contact CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.Contact _CreatedBy;
        partial void OnCreatedByChanging(global::Terrasoft.Configuration.OData.Contact value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedBy")]
        public virtual global::Terrasoft.Configuration.OData.Contact ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.Contact _ModifiedBy;
        partial void OnModifiedByChanging(global::Terrasoft.Configuration.OData.Contact value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public virtual global::Terrasoft.Configuration.OData.ReleaseStatus Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ReleaseStatus _Status;
        partial void OnStatusChanging(global::Terrasoft.Configuration.OData.ReleaseStatus value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Type")]
        public virtual global::Terrasoft.Configuration.OData.ReleaseType Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ReleaseType _Type;
        partial void OnTypeChanging(global::Terrasoft.Configuration.OData.ReleaseType value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Priority in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Priority")]
        public virtual global::Terrasoft.Configuration.OData.ReleasePriority Priority
        {
            get
            {
                return this._Priority;
            }
            set
            {
                this.OnPriorityChanging(value);
                this._Priority = value;
                this.OnPriorityChanged();
                this.OnPropertyChanged("Priority");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ReleasePriority _Priority;
        partial void OnPriorityChanging(global::Terrasoft.Configuration.OData.ReleasePriority value);
        partial void OnPriorityChanged();
        /// <summary>
        /// There are no comments for Property ChangeCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ChangeCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Change> ChangeCollectionByRelease
        {
            get
            {
                return this._ChangeCollectionByRelease;
            }
            set
            {
                this.OnChangeCollectionByReleaseChanging(value);
                this._ChangeCollectionByRelease = value;
                this.OnChangeCollectionByReleaseChanged();
                this.OnPropertyChanged("ChangeCollectionByRelease");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Change> _ChangeCollectionByRelease = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Change>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnChangeCollectionByReleaseChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Change> value);
        partial void OnChangeCollectionByReleaseChanged();
        /// <summary>
        /// There are no comments for Property ActivityCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ActivityCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Activity> ActivityCollectionByRelease
        {
            get
            {
                return this._ActivityCollectionByRelease;
            }
            set
            {
                this.OnActivityCollectionByReleaseChanging(value);
                this._ActivityCollectionByRelease = value;
                this.OnActivityCollectionByReleaseChanged();
                this.OnPropertyChanged("ActivityCollectionByRelease");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Activity> _ActivityCollectionByRelease = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Activity>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnActivityCollectionByReleaseChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.Activity> value);
        partial void OnActivityCollectionByReleaseChanged();
        /// <summary>
        /// There are no comments for Property ReleaseConfItemCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseConfItemCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseConfItem> ReleaseConfItemCollectionByRelease
        {
            get
            {
                return this._ReleaseConfItemCollectionByRelease;
            }
            set
            {
                this.OnReleaseConfItemCollectionByReleaseChanging(value);
                this._ReleaseConfItemCollectionByRelease = value;
                this.OnReleaseConfItemCollectionByReleaseChanged();
                this.OnPropertyChanged("ReleaseConfItemCollectionByRelease");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseConfItem> _ReleaseConfItemCollectionByRelease = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseConfItem>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnReleaseConfItemCollectionByReleaseChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseConfItem> value);
        partial void OnReleaseConfItemCollectionByReleaseChanged();
        /// <summary>
        /// There are no comments for Property ReleaseFileCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseFileCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseFile> ReleaseFileCollectionByRelease
        {
            get
            {
                return this._ReleaseFileCollectionByRelease;
            }
            set
            {
                this.OnReleaseFileCollectionByReleaseChanging(value);
                this._ReleaseFileCollectionByRelease = value;
                this.OnReleaseFileCollectionByReleaseChanged();
                this.OnPropertyChanged("ReleaseFileCollectionByRelease");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseFile> _ReleaseFileCollectionByRelease = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseFile>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnReleaseFileCollectionByReleaseChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseFile> value);
        partial void OnReleaseFileCollectionByReleaseChanged();
        /// <summary>
        /// There are no comments for Property ReleaseInFolderCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseInFolderCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseInFolder> ReleaseInFolderCollectionByRelease
        {
            get
            {
                return this._ReleaseInFolderCollectionByRelease;
            }
            set
            {
                this.OnReleaseInFolderCollectionByReleaseChanging(value);
                this._ReleaseInFolderCollectionByRelease = value;
                this.OnReleaseInFolderCollectionByReleaseChanged();
                this.OnPropertyChanged("ReleaseInFolderCollectionByRelease");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseInFolder> _ReleaseInFolderCollectionByRelease = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseInFolder>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnReleaseInFolderCollectionByReleaseChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseInFolder> value);
        partial void OnReleaseInFolderCollectionByReleaseChanged();
        /// <summary>
        /// There are no comments for Property ReleaseInTagCollectionByEntity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseInTagCollectionByEntity")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseInTag> ReleaseInTagCollectionByEntity
        {
            get
            {
                return this._ReleaseInTagCollectionByEntity;
            }
            set
            {
                this.OnReleaseInTagCollectionByEntityChanging(value);
                this._ReleaseInTagCollectionByEntity = value;
                this.OnReleaseInTagCollectionByEntityChanged();
                this.OnPropertyChanged("ReleaseInTagCollectionByEntity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseInTag> _ReleaseInTagCollectionByEntity = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseInTag>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnReleaseInTagCollectionByEntityChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseInTag> value);
        partial void OnReleaseInTagCollectionByEntityChanged();
        /// <summary>
        /// There are no comments for Property ReleaseServiceItemCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseServiceItemCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseServiceItem> ReleaseServiceItemCollectionByRelease
        {
            get
            {
                return this._ReleaseServiceItemCollectionByRelease;
            }
            set
            {
                this.OnReleaseServiceItemCollectionByReleaseChanging(value);
                this._ReleaseServiceItemCollectionByRelease = value;
                this.OnReleaseServiceItemCollectionByReleaseChanged();
                this.OnPropertyChanged("ReleaseServiceItemCollectionByRelease");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseServiceItem> _ReleaseServiceItemCollectionByRelease = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseServiceItem>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnReleaseServiceItemCollectionByReleaseChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseServiceItem> value);
        partial void OnReleaseServiceItemCollectionByReleaseChanged();
        /// <summary>
        /// There are no comments for Property ReleaseTeamCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ReleaseTeamCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseTeam> ReleaseTeamCollectionByRelease
        {
            get
            {
                return this._ReleaseTeamCollectionByRelease;
            }
            set
            {
                this.OnReleaseTeamCollectionByReleaseChanging(value);
                this._ReleaseTeamCollectionByRelease = value;
                this.OnReleaseTeamCollectionByReleaseChanged();
                this.OnPropertyChanged("ReleaseTeamCollectionByRelease");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseTeam> _ReleaseTeamCollectionByRelease = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseTeam>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnReleaseTeamCollectionByReleaseChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ReleaseTeam> value);
        partial void OnReleaseTeamCollectionByReleaseChanged();
        /// <summary>
        /// There are no comments for Property ScheduledDateCollectionByRelease in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ScheduledDateCollectionByRelease")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ScheduledDate> ScheduledDateCollectionByRelease
        {
            get
            {
                return this._ScheduledDateCollectionByRelease;
            }
            set
            {
                this.OnScheduledDateCollectionByReleaseChanging(value);
                this._ScheduledDateCollectionByRelease = value;
                this.OnScheduledDateCollectionByReleaseChanged();
                this.OnPropertyChanged("ScheduledDateCollectionByRelease");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ScheduledDate> _ScheduledDateCollectionByRelease = new global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ScheduledDate>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnScheduledDateCollectionByReleaseChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Terrasoft.Configuration.OData.ScheduledDate> value);
        partial void OnScheduledDateCollectionByReleaseChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
