//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 09/11/2021 14:00:59
namespace Terrasoft.Configuration.OData
{
    /// <summary>
    /// There are no comments for VwProcessDashboardSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("VwProcessDashboardSingle")]
    public partial class VwProcessDashboardSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<VwProcessDashboard>
    {
        /// <summary>
        /// Initialize a new VwProcessDashboardSingle object.
        /// </summary>
        public VwProcessDashboardSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new VwProcessDashboardSingle object.
        /// </summary>
        public VwProcessDashboardSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new VwProcessDashboardSingle object.
        /// </summary>
        public VwProcessDashboardSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<VwProcessDashboard> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for ProcessElement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessElement")]
        public virtual global::Terrasoft.Configuration.OData.SysProcessElementDataSingle ProcessElement
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ProcessElement == null))
                {
                    this._ProcessElement = new global::Terrasoft.Configuration.OData.SysProcessElementDataSingle(this.Context, GetPath("ProcessElement"));
                }
                return this._ProcessElement;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.SysProcessElementDataSingle _ProcessElement;
        /// <summary>
        /// There are no comments for ProcessData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessData")]
        public virtual global::Terrasoft.Configuration.OData.SysProcessDataSingle ProcessData
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ProcessData == null))
                {
                    this._ProcessData = new global::Terrasoft.Configuration.OData.SysProcessDataSingle(this.Context, GetPath("ProcessData"));
                }
                return this._ProcessData;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.SysProcessDataSingle _ProcessData;
        /// <summary>
        /// There are no comments for Owner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Owner")]
        public virtual global::Terrasoft.Configuration.OData.ContactSingle Owner
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Owner == null))
                {
                    this._Owner = new global::Terrasoft.Configuration.OData.ContactSingle(this.Context, GetPath("Owner"));
                }
                return this._Owner;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ContactSingle _Owner;
        /// <summary>
        /// There are no comments for ElementOwner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ElementOwner")]
        public virtual global::Terrasoft.Configuration.OData.ContactSingle ElementOwner
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ElementOwner == null))
                {
                    this._ElementOwner = new global::Terrasoft.Configuration.OData.ContactSingle(this.Context, GetPath("ElementOwner"));
                }
                return this._ElementOwner;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ContactSingle _ElementOwner;
        /// <summary>
        /// There are no comments for ProcessOwner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessOwner")]
        public virtual global::Terrasoft.Configuration.OData.ContactSingle ProcessOwner
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ProcessOwner == null))
                {
                    this._ProcessOwner = new global::Terrasoft.Configuration.OData.ContactSingle(this.Context, GetPath("ProcessOwner"));
                }
                return this._ProcessOwner;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.ContactSingle _ProcessOwner;
    }
    /// <summary>
    /// There are no comments for VwProcessDashboard in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.EntitySet("VwProcessDashboard")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("VwProcessDashboard")]
    public partial class VwProcessDashboard : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new VwProcessDashboard object.
        /// </summary>
        /// <param name="processName">Initial value of ProcessName.</param>
        /// <param name="elementCaption">Initial value of ElementCaption.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static VwProcessDashboard CreateVwProcessDashboard(string processName, string elementCaption)
        {
            VwProcessDashboard vwProcessDashboard = new VwProcessDashboard();
            vwProcessDashboard.ProcessName = processName;
            vwProcessDashboard.ElementCaption = elementCaption;
            return vwProcessDashboard;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public virtual global::System.Nullable<global::System.Guid> Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _Id;
        partial void OnIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ProcessElementId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessElementId")]
        public virtual global::System.Nullable<global::System.Guid> ProcessElementId
        {
            get
            {
                return this._ProcessElementId;
            }
            set
            {
                this.OnProcessElementIdChanging(value);
                this._ProcessElementId = value;
                this.OnProcessElementIdChanged();
                this.OnPropertyChanged("ProcessElementId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ProcessElementId;
        partial void OnProcessElementIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnProcessElementIdChanged();
        /// <summary>
        /// There are no comments for Property ProcessDataId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessDataId")]
        public virtual global::System.Nullable<global::System.Guid> ProcessDataId
        {
            get
            {
                return this._ProcessDataId;
            }
            set
            {
                this.OnProcessDataIdChanging(value);
                this._ProcessDataId = value;
                this.OnProcessDataIdChanged();
                this.OnPropertyChanged("ProcessDataId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ProcessDataId;
        partial void OnProcessDataIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnProcessDataIdChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property ProcessName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessName")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ProcessName is required.")]
        public virtual string ProcessName
        {
            get
            {
                return this._ProcessName;
            }
            set
            {
                this.OnProcessNameChanging(value);
                this._ProcessName = value;
                this.OnProcessNameChanged();
                this.OnPropertyChanged("ProcessName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ProcessName;
        partial void OnProcessNameChanging(string value);
        partial void OnProcessNameChanged();
        /// <summary>
        /// There are no comments for Property ElementCaption in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ElementCaption")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ElementCaption is required.")]
        public virtual string ElementCaption
        {
            get
            {
                return this._ElementCaption;
            }
            set
            {
                this.OnElementCaptionChanging(value);
                this._ElementCaption = value;
                this.OnElementCaptionChanged();
                this.OnPropertyChanged("ElementCaption");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ElementCaption;
        partial void OnElementCaptionChanging(string value);
        partial void OnElementCaptionChanged();
        /// <summary>
        /// There are no comments for Property EntitySchemaUId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EntitySchemaUId")]
        public virtual global::System.Nullable<global::System.Guid> EntitySchemaUId
        {
            get
            {
                return this._EntitySchemaUId;
            }
            set
            {
                this.OnEntitySchemaUIdChanging(value);
                this._EntitySchemaUId = value;
                this.OnEntitySchemaUIdChanged();
                this.OnPropertyChanged("EntitySchemaUId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _EntitySchemaUId;
        partial void OnEntitySchemaUIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnEntitySchemaUIdChanged();
        /// <summary>
        /// There are no comments for Property EntityId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EntityId")]
        public virtual global::System.Nullable<global::System.Guid> EntityId
        {
            get
            {
                return this._EntityId;
            }
            set
            {
                this.OnEntityIdChanging(value);
                this._EntityId = value;
                this.OnEntityIdChanged();
                this.OnPropertyChanged("EntityId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _EntityId;
        partial void OnEntityIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnEntityIdChanged();
        /// <summary>
        /// There are no comments for Property ProcessElementEntitySchemaUId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessElementEntitySchemaUId")]
        public virtual global::System.Nullable<global::System.Guid> ProcessElementEntitySchemaUId
        {
            get
            {
                return this._ProcessElementEntitySchemaUId;
            }
            set
            {
                this.OnProcessElementEntitySchemaUIdChanging(value);
                this._ProcessElementEntitySchemaUId = value;
                this.OnProcessElementEntitySchemaUIdChanged();
                this.OnPropertyChanged("ProcessElementEntitySchemaUId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ProcessElementEntitySchemaUId;
        partial void OnProcessElementEntitySchemaUIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnProcessElementEntitySchemaUIdChanged();
        /// <summary>
        /// There are no comments for Property ProcessElementEntityId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessElementEntityId")]
        public virtual global::System.Nullable<global::System.Guid> ProcessElementEntityId
        {
            get
            {
                return this._ProcessElementEntityId;
            }
            set
            {
                this.OnProcessElementEntityIdChanging(value);
                this._ProcessElementEntityId = value;
                this.OnProcessElementEntityIdChanged();
                this.OnPropertyChanged("ProcessElementEntityId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ProcessElementEntityId;
        partial void OnProcessElementEntityIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnProcessElementEntityIdChanged();
        /// <summary>
        /// There are no comments for Property ProcessElementSchemaUId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessElementSchemaUId")]
        public virtual global::System.Nullable<global::System.Guid> ProcessElementSchemaUId
        {
            get
            {
                return this._ProcessElementSchemaUId;
            }
            set
            {
                this.OnProcessElementSchemaUIdChanging(value);
                this._ProcessElementSchemaUId = value;
                this.OnProcessElementSchemaUIdChanged();
                this.OnPropertyChanged("ProcessElementSchemaUId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ProcessElementSchemaUId;
        partial void OnProcessElementSchemaUIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnProcessElementSchemaUIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedOn")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property OwnerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OwnerId")]
        public virtual global::System.Nullable<global::System.Guid> OwnerId
        {
            get
            {
                return this._OwnerId;
            }
            set
            {
                this.OnOwnerIdChanging(value);
                this._OwnerId = value;
                this.OnOwnerIdChanged();
                this.OnPropertyChanged("OwnerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _OwnerId;
        partial void OnOwnerIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnOwnerIdChanged();
        /// <summary>
        /// There are no comments for Property ElementOwnerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ElementOwnerId")]
        public virtual global::System.Nullable<global::System.Guid> ElementOwnerId
        {
            get
            {
                return this._ElementOwnerId;
            }
            set
            {
                this.OnElementOwnerIdChanging(value);
                this._ElementOwnerId = value;
                this.OnElementOwnerIdChanged();
                this.OnPropertyChanged("ElementOwnerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ElementOwnerId;
        partial void OnElementOwnerIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnElementOwnerIdChanged();
        /// <summary>
        /// There are no comments for Property ProcessOwnerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessOwnerId")]
        public virtual global::System.Nullable<global::System.Guid> ProcessOwnerId
        {
            get
            {
                return this._ProcessOwnerId;
            }
            set
            {
                this.OnProcessOwnerIdChanging(value);
                this._ProcessOwnerId = value;
                this.OnProcessOwnerIdChanged();
                this.OnPropertyChanged("ProcessOwnerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ProcessOwnerId;
        partial void OnProcessOwnerIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnProcessOwnerIdChanged();
        /// <summary>
        /// There are no comments for Property ProcessSchemaElementUId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessSchemaElementUId")]
        public virtual global::System.Nullable<global::System.Guid> ProcessSchemaElementUId
        {
            get
            {
                return this._ProcessSchemaElementUId;
            }
            set
            {
                this.OnProcessSchemaElementUIdChanging(value);
                this._ProcessSchemaElementUId = value;
                this.OnProcessSchemaElementUIdChanged();
                this.OnPropertyChanged("ProcessSchemaElementUId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ProcessSchemaElementUId;
        partial void OnProcessSchemaElementUIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnProcessSchemaElementUIdChanged();
        /// <summary>
        /// There are no comments for Property ProcessElement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessElement")]
        public virtual global::Terrasoft.Configuration.OData.SysProcessElementData ProcessElement
        {
            get
            {
                return this._ProcessElement;
            }
            set
            {
                this.OnProcessElementChanging(value);
                this._ProcessElement = value;
                this.OnProcessElementChanged();
                this.OnPropertyChanged("ProcessElement");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.SysProcessElementData _ProcessElement;
        partial void OnProcessElementChanging(global::Terrasoft.Configuration.OData.SysProcessElementData value);
        partial void OnProcessElementChanged();
        /// <summary>
        /// There are no comments for Property ProcessData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessData")]
        public virtual global::Terrasoft.Configuration.OData.SysProcessData ProcessData
        {
            get
            {
                return this._ProcessData;
            }
            set
            {
                this.OnProcessDataChanging(value);
                this._ProcessData = value;
                this.OnProcessDataChanged();
                this.OnPropertyChanged("ProcessData");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.SysProcessData _ProcessData;
        partial void OnProcessDataChanging(global::Terrasoft.Configuration.OData.SysProcessData value);
        partial void OnProcessDataChanged();
        /// <summary>
        /// There are no comments for Property Owner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Owner")]
        public virtual global::Terrasoft.Configuration.OData.Contact Owner
        {
            get
            {
                return this._Owner;
            }
            set
            {
                this.OnOwnerChanging(value);
                this._Owner = value;
                this.OnOwnerChanged();
                this.OnPropertyChanged("Owner");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.Contact _Owner;
        partial void OnOwnerChanging(global::Terrasoft.Configuration.OData.Contact value);
        partial void OnOwnerChanged();
        /// <summary>
        /// There are no comments for Property ElementOwner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ElementOwner")]
        public virtual global::Terrasoft.Configuration.OData.Contact ElementOwner
        {
            get
            {
                return this._ElementOwner;
            }
            set
            {
                this.OnElementOwnerChanging(value);
                this._ElementOwner = value;
                this.OnElementOwnerChanged();
                this.OnPropertyChanged("ElementOwner");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.Contact _ElementOwner;
        partial void OnElementOwnerChanging(global::Terrasoft.Configuration.OData.Contact value);
        partial void OnElementOwnerChanged();
        /// <summary>
        /// There are no comments for Property ProcessOwner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessOwner")]
        public virtual global::Terrasoft.Configuration.OData.Contact ProcessOwner
        {
            get
            {
                return this._ProcessOwner;
            }
            set
            {
                this.OnProcessOwnerChanging(value);
                this._ProcessOwner = value;
                this.OnProcessOwnerChanged();
                this.OnPropertyChanged("ProcessOwner");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Terrasoft.Configuration.OData.Contact _ProcessOwner;
        partial void OnProcessOwnerChanging(global::Terrasoft.Configuration.OData.Contact value);
        partial void OnProcessOwnerChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
